
import time
print("In This Python Script We Will Take Input From User And Display It Using Print() Function.")
time.sleep(3)
Name = input("Enter your Name: ")
time.sleep(1)
print("I Am Taking Your Name As Input...")
time.sleep(2)
print("Hello, " + Name + "! Welcome to the Python world.")
time.sleep(2)

print("In Next Script We Will Take Two Numbers From User And Display Their Sum,Subtraction,Product And Division.")
time.sleep(3)
N1=int(input("Enter First Number: "))
N2=int(input("Enter Second Number: "))
time.sleep(2)
print("I Am Calculating The Sum,Subtraction,Product And Division Of Two Numbers...")
time.sleep(2)
print("Please Wait...")
time.sleep(2)
print("And The Result Is...")
time.sleep(2)
print("Sum of Two Numbers is: ", N1+N2, "\nSubstraction of two number is : " ,N1-N2, "\n Product of two number is : ", N1*N2, "\n Division of two number is : ", N1/N2)
time.sleep(3)
print("Thank You For Using This Python Script. Have A Great Day!")